Remove PrecompileWeb and .suo files
googlegsa/samlbridge pull request #30
Opened 2017-05-06 00:10 UTC by lavanyachandramouli

2017-05-06 00:33 UTC, wiarlawd requested changes
Be careful with the commit message. You can't start with two adjacent lines like that. It looks like GitHub (but not git) is just ignoring the second line. You must have a 58 character summary line, optionally followed by a blank line and an extended description.

John L

2017-05-06 00:33 UTC, wiarlawd commented on .gitignore
> +*.suo
You're going to want to add /PrecompiledWeb/ here as well, if this is where the solution will drop the files as before.

2017-05-08 22:10 UTC, lavanyachandramouli commented on .gitignore
> +*.suo
Done.

2017-05-08 22:18 UTC, wiarlawd approved these changes
LGTM

2017-05-09 16:21 UTC, merged